/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.it.example.rest;


import static com.it.example.utilities.StringUtils.join;
import static com.it.example.utilities.StringUtils.split;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.LinkedList;

@SpringBootApplication
public class ExampleRestApplication {
    public static void main(String[] args) {
        SpringApplication.run(ExampleRestApplication.class);
    }
}
