/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.it.example.rest;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ExampleRestApplication {
    public static void main(String[] args) {
        SpringApplication.run(ExampleRestApplication.class);
    }
}
