/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.it.example.java-common-library-conventions")
}

dependencies {
    // Internal modules dependencies
    api(project(":domain:contract"))
    implementation(project(":domain:mediator"))

    // External dependencies

}