/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.it.example.java-spring-application-conventions")
}

dependencies {

    // Internal modules dependencies
    implementation(project(":domain:contract"))
    implementation(project(":domain:core"))

    implementation(project(":application:rest:contract"))
    implementation(project(":infrastructure:configuration"))
    implementation(project(":infrastructure:persistence"))
    implementation(project(":infrastructure:events"))
    implementation(project(":infrastructure:clients"))

    // External dependencies
    implementation("org.springframework.boot:spring-boot-starter-web")
}
