/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.it.example.java-spring-library-conventions")
}

dependencies {
    // Internal modules dependencies
    implementation(project(":domain:contract"))

    // External dependencies

}

application {
    // Define the main class for the application.
    mainClass.set("com.it.example.app.App")
}
