/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.it.example.java-spring-application-conventions")
}

dependencies {

    // Internal modules dependencies
    api(project(":domain:core"))

    implementation(project(":application:grpc:contract"))
    implementation(project(":infrastruture:configuration"))
    implementation(project(":infrastruture:persistence"))
    implementation(project(":infrastruture:events"))
    implementation(project(":infrastruture:clients"))

    // External dependencies
}

