/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.it.example.rest.controller;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
